# Generated by Django 3.2.4 on 2021-06-26 18:04

from django.db import migrations
import django_db_views.migration_functions
import django_db_views.operations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        django_db_views.operations.ViewRunPython(
            code=django_db_views.migration_functions.ForwardViewMigration('select row_number() over() as id\n             , ms.id as room_id\n             , ms.name\n             , ms.address\n             , ms.price\n             , ms.latitude\n             , ms.longitude\n             , ms.max_people\n             , ms.description\n             , ms.guest_type\n             , ns.check_in_date\n             , ns.check_out_date\n          from rooms ms\n          left join (select room_id\n                          , max(check_in_date) as check_in_date\n                          , max(check_out_date) as check_out_date\n                       from room_reservations\n                      group by room_id) ns \n                 on ms.id = ns.room_id', 'rooms_view', engine='django.db.backends.mysql'),
            reverse_code=django_db_views.migration_functions.BackwardViewMigration('', 'rooms_view', engine='django.db.backends.mysql'),
            atomic=False,
        ),
    ]
