# Generated by Django 3.2.4 on 2021-07-05 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20210701_1140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomView',
        ),
    ]
