from .base import *
from my_settings import LOCAL_SECRET_KEY, LOCAL_DATABASES, LOCAL_CACHES, LOGGING

SECRET_KEY = LOCAL_SECRET_KEY

DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1']

DATABASES = LOCAL_DATABASES

CACHES = LOCAL_CACHES

LOGGING = LOGGING