from .base import *
from my_settings import PROD_SECRET_KEY, PROD_DATABASES, PROD_CACHES

SECRET_KEY = PROD_SECRET_KEY

DEBUG = False

ALLOWED_HOSTS = ['*']

DATABASES = PROD_DATABASES

CACHES = PROD_CACHES