from .base import *
from my_settings import LOCAL_SECRET_KEY, LOCAL_DATABASES, LOCAL_CACHES, LOGGING, ALGORITHM

SECRET_KEY = LOCAL_SECRET_KEY

DEBUG = True

ALLOWED_HOSTS = ['*']

DATABASES = LOCAL_DATABASES

CACHES = LOCAL_CACHES

LOGGING = LOGGING

ALGORITHM = ALGORITHM